import datetime


CURRENT_TIME = datetime.datetime.now()
#TODO check for corner case of time here
LAST_UPDATED_TIME = datetime.datetime.now()
# COLLECTIONS_NAME = ["location_states_v1", "location_districts_v1"]
# COLLECTIONS_NAME = ["location_states_v1", "location_districts_v1", "location_cities_v1"]

MULTILINGUAL_NAMES_DICT = {'name_bn': 1,
						   'name_en': 1,
						   'name_gu': 1,
						   'name_hi': 1,
						   'name_kn': 1,
						   'name_ml': 1,
						   'name_mr': 1,
						   'name_or': 1,
						   'name_pa': 1,
						   'name_ta': 1,
						   'name_te': 1,
						   'name_ur': 1,
						   'name_as':1,
						   'alternate_names_bn': 1,
						   'alternate_names_en': 1,
						   'alternate_names_gu': 1,
						   'alternate_names_hi': 1,
						   'alternate_names_kn': 1,
						   'alternate_names_ml': 1,
						   'alternate_names_mr': 1,
						   'alternate_names_or': 1,
						   'alternate_names_pa': 1,
						   'alternate_names_ta': 1,
						   'alternate_names_te': 1,
						   'alternate_names_ur': 1,
						   'alternate_names_as':1,
						   'id':1,
						   '_id':0}

BLOCK_DICT = {'hi': {"सागर", "सूरत", "पुरी", "कटरा", "गया", "आरा", "कृष्णा", "निर्मल", "मंडी", "धुले", "हासन", "फेक", "बौध", "कोटा",
					 "सलेम", "नदिया", "बांकुड़ा", "पन्ना", "गुना", "बस्ती", "संभल", "दुर्ग", "बांका", "लोहित"},
			  "en": {"sagar", "solan", "chandel", "erode", "krishna", "nirmal", "hassan", "salem", "lohit"},
			  "ur": {"کرشن", "نرمل", "ہاسن", "سیلم", "لوہت", "بانکا"},
			  "te": {"కృష్ణా", "నిర్మల్"},
			  "kn": {"ಹಾಸನ"},
			  "ta": {"சேலம்"},
			  "as": {"লোহিত"},
			  "bn": {"বাঁকা"}
			  }

#patch added cities 
#TODO: to add in mongo db as alternate_names_en since the spelling is mismatched e.g. Darjeeling is in mongo Darjiling which is referenced from geonames

MISSED_CITIES_NAMES = { "alipurduar" : "location_districts_413",
						"আলিপুরদুয়ার" :"location_districts_413",
						"अलिपुरद्वार" :"location_districts_413",
						"അലിപൂർദുർ" :"location_districts_413",
						"अलिपूरद्वार" :"location_districts_413",
						"அலிப்பூர்துவார்" :"location_districts_413",
						"అలిపురుదుయర్" :"location_districts_413",
						"علی پور دوار" :"location_districts_413",
						"darjeeling":"location_cities_2563",
						"দার্জিলিং":"location_cities_2563",
						"দার্জিলিং":"location_cities_2563",
						"દાર્જિલિંગ":"location_cities_2563",
						"दार्जिलिंग":"location_cities_2563",
						"ಡಾರ್ಜಿಲಿಂಗ್":"location_cities_2563",
						"ഡാർജിലിംഗ്":"location_cities_2563",
						"दार्जीलिंग":"location_cities_2563",
						"ਦਾਰਜੀਲਿੰਗ":"location_cities_2563",
						"டார்ஜீலிங்":"location_cities_2563",
						"డార్జిలింగ్":"location_cities_2563",
						"دار جیلنگ":"location_cities_2563",
						"jalpaiguri":"location_districts_402",
						"જલપાઈગુડી":"location_districts_402",
						"জলপাইগুড়ি":"location_districts_402",
						"जलपाईगुड़ी":"location_districts_402",
						"ജൽപായ്ഗുരി":"location_districts_402",
						"जलपाइगुडी":"location_districts_402",
						"ଜଳପାଇଗୁଡ଼ି":"location_districts_402",
						"ஜல்பாய்குரி":"location_districts_402",
						"జల్పైగురి":"location_districts_402",
						"جلپیگری":"location_districts_402",
						"nadia":"location_districts_407",
						"নদিয়া":"location_districts_407",
						"નદિયા":"location_districts_407",
						"नदिया":"location_districts_407",
						"നാദിയ":"location_districts_407",
						"नदिया":"location_districts_407",
						"ନଦିଆ":"location_districts_407",
						"நதியா":"location_districts_407",
						"నాడియా":"location_districts_407",
						"ندیا":"location_districts_407",
						"medinipur":"location_districts_422",
						"মেদিনীপুর":"location_districts_422",
						"મેદિનીપુર":"location_districts_422",
						"मेदिनीपुर":"location_districts_422",
						"ಮೇದಿನಿಪುರ್":"location_districts_422",
						"മിഡ്നാപൂർ":"location_districts_422",
						"मिदनापोर":"location_districts_422",
						"மிடினப்போர்":"location_districts_422",
						"మిడ్నాపూర్":"location_districts_422",
						"مدناپور، مغربی بنگال":"location_districts_422",
						"murshidabad":"location_cities_1228",
						"মুর্শিদাবাদ":"location_cities_1228",
						"મુર્શિદાબાદ":"location_cities_1228",
						"मुर्शिदाबाद":"location_cities_1228",
						"ಮುರ್ಷಿದಾಬಾದ್":"location_cities_1228",
						"മുർഷിദാബാദ്":"location_cities_1228",
						"முர்ஷிதாபாத்":"location_cities_1228",
						"ముర్సిదాబాద్":"location_cities_1228",
						"مرشد آباد":"location_cities_1228",
						"haora":"location_cities_2182",
						"হাওড়া":"location_cities_2182",
						"હાવડા":"location_cities_2182",
						"हावड़ा":"location_cities_2182",
						"ಹೌರಾ":"location_cities_2182",
						"हावरा":"location_cities_2182",
						"ହାଓଡ଼ା":"location_cities_2182",
						"ਹਾਵੜਾ":"location_cities_2182",
						"ஹவுரா":"location_cities_2182",
						"హౌరా":"location_cities_2182",
						"ہاوڑا":"location_cities_2182",
						"hugli":"location_cities_2117",
						"হুগলী":"location_cities_2117"
						}

STATE_LANGUAGE = {'gu': {'location_states_1', 'location_states_34', 'location_states_36', 'location_states_15'},
				  'mr': {'location_states_15', 'location_states_1', 'location_states_34', 'location_states_36', 'location_states_7', 'location_states_14', 'location_states_12', 'location_states_38'},
				  'te': {'location_states_2', 'location_states_12', 'location_states_23', 'location_states_32', 'location_states_37', 'location_states_38'},
				  'kn': {'location_states_7', 'location_states_12', 'location_states_23', 'location_states_37', 'location_states_38'},
				  'ta': {'location_states_2', 'location_states_12', 'location_states_23', 'location_states_32', 'location_states_37'},
				  'bn': {'location_states_3', 'location_states_4', 'location_states_5', 'location_states_6', 'location_states_11', 'location_states_16', 'location_states_17', 'location_states_18', 'location_states_20', 'location_states_21', 'location_states_26', 'location_states_27', 'location_states_28', 'location_states_29', 'location_states_32'},
				  'or': {'location_states_6', 'location_states_29'},
				  'ml': {'location_states_13', 'location_states_23', 'location_states_31', 'location_states_32'},
				  'pa': {'location_states_8', 'location_states_9', 'location_states_10', 'location_states_18', 'location_states_22', 'location_states_30', 'location_states_33', 'location_states_35'},
				  'as': {'location_states_3', 'location_states_4', 'location_states_21', 'location_states_28'}
				  }
